set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'altercation/vim-colors-solarized'
Plugin 'elzr/vim-json'
Plugin 'scrooloose/syntastic'
Plugin 'joukevandermaas/vim-ember-hbs'
Plugin 'hashivim/vim-terraform'
Plugin 'PProvost/vim-ps1'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" VIM Configuration
syntax on
set expandtab
set shiftwidth=2
set softtabstop=2
set laststatus=2
set colorcolumn=80
set number
"set termguicolors
filetype plugin indent on
colorscheme solarized

"set paste
set backspace=indent,eol,start

" Airline
let g:airline_theme='solarized'
let g:airline_powerline_fonts = 1
set t_Co=256

" vim-json configuration
let g:vim_markdown_folding_disabled = 1
let g:vim_json_syntax_conceal = 0

" solarized configuration
let g:solarized_termtrans = 1

"" Syntastic Configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_check_on_wq = 1
let g:syntastic_ruby_checkers = ['rubocop', 'foodcritic']
let g:syntastic_ruby_rubocop_exec = '/usr/local/bin/cookstyle'

" vim-terraform
let g:terraform_align=1

" Yank text to the OS X clipboard
set clipboard=unnamed
noremap y "*y
noremap yy "*Y

" Preserve indentation while pasting text from the OS X clipboard
noremap <leader>p :set paste<CR>:put  *<CR>:set nopaste<CR>
au BufRead,BufNewFile *.json setf json

autocmd BufRead COMMIT_EDITMSG setlocal spell spelllang=en_us
autocmd BufNewFile,BufRead *.md,*.mkd,*.markdown set spell spelllang=en_us
