---
# MacOS defaults configuration - allows users to read, write,
# and delete Mac OS X user defaults

- name: set MacOS defaults and behavior
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ osx_defaults }}"
