---
# doing configuration

- name: setting up zsh with ZIM
  git:
    repo: https://github.com/zimfw/zimfw.git
    dest: "{{general.local_home}}/.zim"

- name: create GOPATH directory
  file:
    path: "{{general.local_home}}/go"
    state: directory

- name: create nvim autoload directory
  file:
    path: "{{general.local_home}}/.local/share/nvim/site/autoload"
    state: directory

- name: setting up vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{general.local_home}}/.local/share/nvim/site/autoload/plug.vim"
